# Generated by Django 3.2.20 on 2023-08-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Customer',
            new_name='customer',
        ),
    ]
