# Generated by Django 3.2.21 on 2023-11-17 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_customer_review_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '4.Customers'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name_plural': '7.CustomerAddresses'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '5.Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': '6.OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': '8.Reviews'},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='base.product')),
            ],
        ),
    ]
