# Generated by Django 3.2.21 on 2023-11-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
