# Generated by Django 3.2.21 on 2023-11-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
